using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bell.Models.Books;


namespace Bell.Models
{
    public class DbInitializer
    {
        public static void Seed(AppDbContext context, IBookRepository bookRepository)
        {

            if (!context.Books.Any())    // add these books if the db Book table is empty
            {
                
                context.AddRange
                (
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "The Great Gatsby", Author = "F. Scott Fitzgerald ", Description = "The Great Gatsby, F. Scott Fitzgerald’s third book, stands as the supreme achievement of his career. First published in 1925, this quintessential novel of the Jazz Age has been acclaimed by generations of readers. The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted “gin was the national drink and sex the national obsession,” it is an exquisitely crafted tale of America in the 1920s.", BookCoverThumbnailUrl = "Content/images/tgg.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Catch-22", Author = "Joseph Heller", Description = "Set in Italy during World War II, this is the story of the incomparable, malingering bombardier, Yossarian, a hero who is furious because thousands of people he has never met are trying to kill him. But his real problem is not the enemy—it is his own army, which keeps increasing the number of missions the men must fly to complete their service. Yet if Yossarian makes any attempt to excuse himself from the perilous missions he’s assigned, he’ll be in violation of Catch-22, a hilariously sinister bureaucratic rule: a man is considered insane if he willingly continues to fly dangerous combat missions, but if he makes a formal request to be removed from duty, he is proven sane and therefore ineligible to be relieved.", BookCoverThumbnailUrl = "Content/images/c22.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "On the Road", Author = "Jack Kerouac", Description = "Inspired by Jack Kerouac's adventures with Neal Cassady, On the Road tells the story of two friends whose cross-country road trips are a quest for meaning and true experience. Written with a mixture of sad-eyed naiveté and wild ambition and imbued with Kerouac's love of America, his compassion for humanity, and his sense of language as jazz, On the Road is the quintessential American vision of freedom and hope, a book that changed American literature and changed anyone who has ever picked it up", BookCoverThumbnailUrl = "Content/images/otr.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "To Kill a Mockingbird", Author = "Harper Lee", Description = "One of the most cherished stories of all time, To Kill a Mockingbird has been translated into more than forty languages, sold more than forty million copies worldwide, served as the basis for an enormously popular motion picture, and was voted one of the best novels of the twentieth century by librarians across the country. A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice, it views a world of great beauty and savage inequities through the eyes of a young girl, as her father—a crusading local lawyer—risks everything to defend a black man unjustly accused of a terrible crime.", BookCoverThumbnailUrl = "Content/images/tkam.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "The Lord of the Rings", Author = "J.R.R. Tolkien", Description = "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins.", BookCoverThumbnailUrl = "Content/images/lotr.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "The Catcher in the Rye", Author = "J. D. Salinger", Description = "There are many voices in this novel: children's voices, adult voices, underground voices-but Holden's voice is the most eloquent of all. Transcending his own vernacular, yet remaining marvelously faithful to it, he issues a perfectly articulated cry of mixed pain and pleasure. However, like most lovers and clowns and poets of the higher orders, he keeps most of the pain to, and for, himself. The pleasure he gives away, or sets aside, with all his heart. It is there for the reader who can handle it to keep", BookCoverThumbnailUrl = "Content/images/tcitr.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Midnight's Children", Author = "Salman Rushdie", Description = "Saleem Sinai is born at the stroke of midnight on August 15, 1947, the very moment of India’s independence. Greeted by fireworks displays, cheering crowds, and Prime Minister Nehru himself, Saleem grows up to learn the ominous consequences of this coincidence. His every act is mirrored and magnified in events that sway the course of national affairs; his health and well-being are inextricably bound to those of his nation; his life is inseparable, at times indistinguishable, from the history of his country. Perhaps most remarkable are the telepathic powers linking him with India’s 1,000 other “midnight’s children,” all born in that initial hour and endowed with magical gifts", BookCoverThumbnailUrl = "Content/images/mc.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Alice's Adventures in Wonderland", Author = "Lewis Carroll", Description = "The story tells of a young girl named Alice falling through a rabbit hole into a fantasy world populated by peculiar, anthropomorphic creatures. The tale plays with logic, giving the story lasting popularity with adults as well as with children. It is considered to be one of the best examples of the literary nonsense genre. Its narrative course, structure, characters, and imagery have been enormously influential in both popular culture and literature, especially in the fantasy genre. ", BookCoverThumbnailUrl = "Content/images/aaiw.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Ulysses", Author = "James Joyce", Description = "Joyce is best known for Ulysses (1922), a landmark work in which the episodes of Homer's Odyssey are paralleled in an array of contrasting literary styles, perhaps most prominent among these the stream of consciousness technique he utilised. Other well-known works are the short-story collection Dubliners (1914), and the novels A Portrait of the Artist as a Young Man (1916) and Finnegans Wake (1939). His other writings include three books of poetry, a play, occasional journalism and his published letters.", BookCoverThumbnailUrl = "Content/images/ujj.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Lord of the Flies ", Author = "William Golding", Description = "At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate. This far from civilization they can do anything they want. Anything. But as order collapses, as strange howls echo in the night, as terror begins its reign, the hope of adventure seems as far removed from reality as the hope of being rescued.", BookCoverThumbnailUrl = "Content/images/lotf.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "The Grapes of Wrath", Author = "John Steinbeck", Description = "First published in 1939, Steinbeck’s Pulitzer Prize-winning epic of the Great Depression chronicles the Dust Bowl migration of the 1930s and tells the story of one Oklahoma farm family, the Joads—driven from their homestead and forced to travel west to the promised land of California. Out of their trials and their repeated collisions against the hard realities of an America divided into Haves and Have-Nots evolves a drama that is intensely human yet majestic in its scale and moral vision, elemental yet plainspoken, tragic but ultimately stirring in its human dignity. A portrait of the conflict between the powerful and the powerless, of one man’s fierce reaction to injustice, and of one woman’s stoical strength, the novel captures the horrors of the Great Depression and probes into the very nature of equality and justice in America. At once a naturalistic epic, captivity narrative, road novel, and transcendental gospel, Steinbeck’s powerful landmark novel is perhaps the most American of American Classics.", BookCoverThumbnailUrl = "Content/images/gow.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "1984", Author = "George Orwell", Description = "Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can’t escape the fact that Big Brother is always watching...", BookCoverThumbnailUrl = "Content/images/1984.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Jane Eyre", Author = "Charlotte Bronte", Description = "Initially published under the pseudonym Currer Bell in 1847, Charlotte Brontë’s Jane Eyreerupted onto the English literary scene, immediately winning the devotion of many of the world’s most renowned writers, including William Makepeace Thackeray, who declared it a work “of great genius.” Widely regarded as a revolutionary novel, Brontë’s masterpiece introduced the world to a radical new type of heroine, one whose defiant virtue and moral courage departed sharply from the more acquiescent and malleable female characters of the day. Passionate, dramatic, and surprisingly modern, Jane Eyre endures as one of the world’s most beloved novels.", BookCoverThumbnailUrl = "Content/images/je.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Moby Dick", Author = "Herman Melville", Description = "With an Introduction and Notes by David Herd. Lecturer in English and American Literature at the University of Kent at Canterbury Moby-Dick is the story of Captain Ahab's quest to avenge the whale that 'reaped' his leg. The quest is an obsession and the novel is a diabolical study of how a man becomes a fanatic. But it is also a hymn to democracy. Bent as the crew is on Ahab s appalling crusade, it is equally the image of a co-operative community at work: all hands dependent on all hands, each individual responsible for the security of each. Among the crew is Ishmael, the novel's narrator, ordinary sailor, and extraordinary reader. Digressive, allusive, vulgar, transcendent, the story Ishmael tells is above all an education: in the practice of whaling, in the art of writing.", BookCoverThumbnailUrl = "Content/images/md.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Mrs. Dalloway", Author = "Virginia Woolf", Description = "In Mrs. Dalloway, the novel on which the movie The Hours was based, Virginia Woolf details Clarissa Dalloway&#8217;s preparations for a party of which she is to be hostess, exploring the hidden springs of thought and action in one day of a woman&#8217;s life. The novel contains some of the most beautiful, complex, incisive and idiosyncratic sentences ever written in English, and that alone would be reason enough to read it.It is one of the most moving, revolutionary artworks of the twentieth century.", BookCoverThumbnailUrl = "Content/images/mdw.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "A Passage to India", Author = "E.M. Forster", Description = "Among the greatest novels of the twentieth century and the basis for director David Lean’s Academy Award-winning film, A Passage to India tells of the clash of cultures in British India after the turn of the century. In exquisite prose, Forster reveals the menace that lurks just beneath the surface of ordinary life, as a common misunderstanding erupts into a devastating affair.", BookCoverThumbnailUrl = "Content/images/apti.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Brave New World", Author = "Aldous Huxley", Description = "Aldous Huxley's profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order–all at the cost of our freedom, full humanity, and perhaps also our souls. “A genius [who] who spent his life decrying the onward march of the Machine” (The New Yorker), Huxley was a man of incomparable talents: equally an artist, a spiritual seeker, and one of history’s keenest observers of human nature and civilization. Brave New World, his masterpiece, has enthralled and terrified millions of readers, and retains its urgent relevance to this day as both a warning to be heeded as we head into tomorrow and as thought-provoking, satisfying work of literature. Written in the shadow of the rise of fascism during the 1930s, Brave New World likewise speaks to a 21st-century world dominated by mass-entertainment, technology, medicine and pharmaceuticals, the arts of persuasion, and the hidden influence of elites. ", BookCoverThumbnailUrl = "Content/images/bnw.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Things Fall Apart", Author = "Chinua Achebe", Description = "Things Fall Apart is the first of three novels in Chinua Achebe's critically acclaimed African Trilogy. It is a classic narrative about Africa's cataclysmic encounter with Europe as it establishes a colonial presence on the continent. Told through the fictional experiences of Okonkwo, a wealthy and fearless Igbo warrior of Umuofia in the late 1800s, Things Fall Apart explores one man's futile resistance to the devaluing of his Igbo traditions by British political andreligious forces and his despair as his community capitulates to the powerful new order", BookCoverThumbnailUrl = "Content/images/tfa.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Frankenstein ", Author = "Mary Shelley", Description = "Few creatures of horror have seized readers' imaginations and held them for so long as the anguished monster of Mary Shelley's Frankenstein. The story of Victor Frankenstein's terrible creation and the havoc it caused has enthralled generations of readers and inspired countless writers of horror and suspense. Considering the novel's enduring success, it is remarkable that it began merely as a whim of Lord Byron's.", BookCoverThumbnailUrl = "Content/images/frank.jpg" },
                    new Book { BookIdent = bookRepository.GenNewBookIdent(), Name = "Robinson Crusoe", Author = "Daniel Defoe", Description = "Robinson Crusoe is a novel by Daniel Defoe, first published on 25 April 1719. The first edition credited the work's protagonist Robinson Crusoe as its author, leading many readers to believe he was a real person and the book a travelogue of true incidents. Epistolary, confessional, and didactic in form, the book is presented as an autobiography of the title character (whose birth name is Robinson Kreutznaer)—a castaway who spends twenty-eight years on a remote tropical desert island near Trinidad, encountering cannibals, captives, and mutineers, before ultimately being rescued. The story has since been thought to be based on the life of Alexander Selkirk, a Scottish castaway who lived for four years on a Pacific island called Más a Tierra, now part of Chile, which was renamed Robinson Crusoe Island in 1966, but various literary sources have also been suggested.", BookCoverThumbnailUrl = "Content/images/robc.jpg" }
                );

                context.SaveChanges();
            }


            /*
             
            if (!context.Loans.Any())    // add some loans if the db Loan table is empty
            {
                context.AddRange
                (
                    new Loan { LoanBookId = 1, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-01"), TimesRenewed = 0, LoanOpen = true },
                    new Loan { LoanBookId = 3, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-01"), TimesRenewed = 1, LoanOpen = true },
                    new Loan { LoanBookId = 5, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-02"), TimesRenewed = 2, LoanOpen = true },
                    new Loan { LoanBookId = 7, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-02"), TimesRenewed = 3, LoanOpen = true },
                    new Loan { LoanBookId = 9, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-03"), TimesRenewed = 0, LoanOpen = true },
                    new Loan { LoanBookId = 10, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-03"), TimesRenewed = 1, LoanOpen = false },
                    new Loan { LoanBookId = 12, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-04"), TimesRenewed = 2, LoanOpen = false },
                    new Loan { LoanBookId = 14, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-04"), TimesRenewed = 3, LoanOpen = false },
                    new Loan { LoanBookId = 16, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-05"), TimesRenewed = 0, LoanOpen = false },
                    new Loan { LoanBookId = 18, UserId = "3c655261-cc4f-47b1-a80d-d7270af226dc", ReturnDate = DateTime.Parse("2012-01-05"), TimesRenewed = 1, LoanOpen = false }
                );

                context.SaveChanges();

            }

            */

        }
    }
}
